import { resolve } from "node:path";

/** Repository root (aurii monorepo). */
export const REPO_ROOT = resolve(import.meta.dir, "../../..");

/** Norwegian Geo product root (`demo/norwegian-geo`). */
export const PRODUCT_ROOT = resolve(import.meta.dir, "..");

export const CORE_DIR = resolve(PRODUCT_ROOT, "core");
export const MODULES_DIR = resolve(PRODUCT_ROOT, "modules");
export const SCRIPTS_DIR = resolve(PRODUCT_ROOT, "scripts");

export function coreDataDir(): string {
	return resolve(CORE_DIR, "data");
}

export function coreSchemaDir(): string {
	return resolve(CORE_DIR, "schemas");
}

export function coreImportDir(): string {
	return resolve(CORE_DIR, "imports");
}

export function coreRawDir(): string {
	return resolve(CORE_DIR, "raw");
}

export function historicalDir(): string {
	return resolve(CORE_DIR, "historical");
}

export function historicalDataDir(): string {
	return resolve(CORE_DIR, "historical/data");
}

export function moduleDir(moduleId: string): string {
	return resolve(MODULES_DIR, moduleId);
}

export function moduleDataDir(moduleId: string): string {
	return resolve(moduleDir(moduleId), "data");
}

export function moduleSchemaDir(moduleId: string): string {
	return resolve(moduleDir(moduleId), "schemas");
}

export function moduleImportDir(moduleId: string): string {
	return resolve(moduleDir(moduleId), "imports");
}

/** Heraldry assets generated by the historical pipeline. */
export function heraldryAssetsDir(): string {
	return resolve(REPO_ROOT, "apps/geo/public/assets/heraldry");
}
